site_name: ML-Git
site_url: "https://hpinc.github.io/ml-git/"
nav:
  - Home:
    - Introduction: index.md
    - Getting Started: first_steps.md
    - Additional Use Cases: advanced_scenarios.md
    - Architecture: 
      - Design: mlgit_internals.md
      - Cache and Objects: centralized_cache_and_objects.md
      - Mutability Helper: mutability_helper.md
      - Plugins: plugins.md
      - Resources Initialization: resources_initialization.md
      - Working With Tabular Data: tabular_data/tabular_data.md
    - Supported Storages:
      - Configurations: storage_configurations.md
      - S3 and MinIO: s3_configurations.md
      - Azure: azure_configurations.md
      - Google Drive: gdrive_configurations.md
    - Commands:
      - Using ML-Git CLI: mlgit_commands.md
      - Using ML-Git API:
        - Quick Start: api/quick_start.md
        - Methods: api/README.md
    - Docker Environment: downloadable_environment.md
  - Contributing to ML-Git: developer_info.md

  
theme:
  name: "material"
  # logo: img/small_icon.png
  # favicon: img/fav_icon.png
  palette:
    primary: light blue
  features:
    - navigation.tabs
    - toc.integrate
markdown_extensions:
  - md_in_html
  - pymdownx.superfences
  - toc:
     permalink: true

plugins:
  - search # necessary for search to work
  - git-revision-date-localized
